# Publish all joint states
# Creates the /joint_states topic necessary in ROS
MOJROBOT:
  # Simulation settings for using moveit_sim_controllers
  moveit_sim_hw_interface:
    joint_model_group: arm
    joint_model_group_pose: pose1
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - prvi_sklep
      - drugi_sklep
    sim_control_mode: 1  # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - prvi_sklep
      - drugi_sklep
    gains:
      prvi_sklep:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      drugi_sklep:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

controller_list:
  - name: MOJROBOT/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - prvi_sklep
      - drugi_sklep