MOJROBOT:
  # publish all joint states:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

MOJROBOT/gazebo_ros_control/pid_gains:
  prvi_sklep: {p: 1000, i: 0,  d: 100}
  drugi_sklep: {p: 1000, i: 0,  d: 100}